services:
  - type: web
    name: scooter-location-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port 8000
    plan: free
